export const GET_ALL_DOGS = "GET_ALL_DOGS"; //traer todos los perros y mostrarlos
export const GET_TEMPER = "GET_TEMPER"; //Traer temperamentos
export const GET_FILTER_TEMPER = "GET_FILTER_TEMPER"; //Filtrado por temperamento
export const GET_DOG = "GET_DOG"; //Raza existente del api o creada por nosotros
export const ORDER_BY_NAME = "ORDER_BY_NAME"; //el orden alfabético
export const ORDER_BY_WEIGHT = "ORDER_BY_WEIGHT"; //orden por peso del perro
export const GET_DETAIL = "GET_DETAIL"; // detalle del perros
export const CLEAR_DETAIL = "CLEAR_DETAIL"; // para limpiar el estado despues de salir de details
export const CLEAR_DOGS = "CLEAR_DOGS"; // borrar estado dogs y allDogs para ingresar al detail mas rapido
